var mongoose = require('mongoose');

var Schema = mongoose.Schema({
    artist: String,
    cmc: String,
    colorIdentity: [],
    colors: [],
    loyalty: Number,
    flavor: String,
    foreignNames: [],
    id: String,
    imageName: String,
    layout: String,
    legalities: [],
    manaCost: String,
    mciNumber: String,
    multiverseid: Number,
    hand: Number,
    life: Number,
    name: String,
    names: [],
    number: String,
    originalText: String,
    originalType: String,
    power: String,
    printings: [],
    rarity: String,
    subtypes: [],
    supertypes: [],
    text: String,
    toughness: String,
    type: String,
    watermark: String,
    border: String,
    releaseDate: String,
    code: String,
    language: String,
    source: String,
    timeshifted: Boolean,
    reserved: Boolean,
    starter: Boolean,
    types: [],
    variations: [],
    rulings: [],
});

module.exports = mongoose.model('Carta', Schema);
